### PR TITLE
rails timezone support

### PR DESCRIPTION
**Pull request by haoxilu**
I think in Rails way, Crono timezone should not dependent on system timezone ,  it should dependent Rails project time zone.

### CODE REVIEW

**Comment by plashchynski** [comment]
Hello @haoxilu 
Thank you for your work. Could you please fix the failing specs?

**Comment by haoxilu** [comment]
Hi, @plashchynski , Could you see this errors? [Travis CI Errors](https://travis-ci.org/plashchynski/crono/jobs/208617556#L57-L62) . 
image
This error is the failure to install Ruby 2.2.6.

**Comment by plashchynski** [comment]
@haoxilu ah, thank you

**Comment by timdorr** [comment]
Just a note, it's a little better to use [`Time.current`](https://github.com/rails/rails/blob/b6ac50b3ee2ff51203774cc0c2647a437237f396/activesupport/lib/active_support/core_ext/time/calculations.rb#L36-L38) in case the host app doesn't have a time zone set.

**Pull request merged**
