### PR TITLE
Convert to Rails engine

### PR DESCRIPTION
**Pull request by cseelus**
First, thanks for this gem. Been using it since ~5 years and it works really reliably.

This PR converts Crono to a [Rails Engine](https://guides.rubyonrails.org/v4.1.1/engines.html#what-are-engines-questionmark). Sinatra (and Haml) are not needed as dependencies for the Web UI anymore.

It also updates Materialize CSS and overhauls the Web UI to make it responsive and display properly on mobile devices:

Before:
Screen Shot 2021-02-14 at 17 52 05

After:
Screen Shot 2021-02-14 at 17 55 35

After (alternative w/o tables, in different branch):
Screen Shot 2021-02-14 at 17 56 00

All tests are green again. A bit of cleanup that I still could do, should this PR be a direction you want to go.

### CODE REVIEW

**Comment by plashchynski** [comment]
Hey @cseelus do you still use this library? Asking because I don't use it for a few years and seeking persons who might be interested in maintaining.

**Comment by cseelus** [comment]
Hi @plashchynski, no problem. Yes, still using it with Rails 7.0.3.

**Comment by cseelus** [comment]
Thanks for merging. If I can help cut a new release for Rubygems, just let me know.

**Comment by plashchynski** [comment]
@cseelus Thank you!  The new release is on the way. Could you please test the current code in the main branch?

**Pull request merged**
